### PR TITLE
Add albums close# 19. Fix auth on reload close# 46

### LINKED ISSUE #19: Albums pages

### LINKED ISSUE #46: Load user on store init

### PR DESCRIPTION
**Pull request by iamprovidence**

### CODE REVIEW

File: src/backend/Aggregator/Domains/DataTransferObjects/Photos/PhotoListDTO.cs [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+{
+    public class PhotoListDTO
+    {
+        public Guid Id { get; set; }
+        public DateTime UploadDate { get; set; }
+
+        public string Name { get; set; }
+        public string Description { get; set; }
+
+        public string PhotoUrl64 { get; set; }
```
Comment (iamprovidence) [inline src/backend/Aggregator/Domains/DataTransferObjects/Photos/PhotoListDTO.cs:13]: Codacy Issue found: [Change this property type to 'System.Uri'.](https://app.codacy.com/manual/iamprovidence/Lama/pullRequest?prid=5020178)

**Comment by iamprovidence** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 11
           

Complexity increasing per file
==============================
- src/backend/LamaAPI/Application/Comments/Events/ClearCommentsOnPhotosDeletedEventHandler.cs  1
- src/backend/LamaAPI/Infrastructure/Configurations/PhotoAlbumConfiguration.cs  1
- src/backend/LamaAPI/API/Middlewares/ErrorWrappingMiddleware.cs  1
- src/backend/Aggregator/Aggregator/ServicesConfiguration/HttpServicesConfiguration.cs  1
- src/backend/Aggregator/HttpServices/Extensions/HttpClientExtensions.cs  1
- src/backend/Aggregator/HttpServices/Services/PhotosService.cs  1
- src/backend/Aggregator/HttpServices/Services/AlbumsService.cs  1
- src/backend/Aggregator/Aggregator/Program.cs  1
- src/backend/LamaAPI/Infrastructure/Identity/AuthService.cs  1
- src/backend/LamaAPI/Application/Albums/Commands/CreateAlbum/CreateAlbumCommandHandler.cs  1
- src/backend/LamaAPI/Application/PhotoAlbums/Queries/GetAlbumPhotos/GetAlbumPhotosQueryHandler.cs  1
- src/backend/LamaAPI/Domains/Entities/PhotoAlbum.cs  1
- src/backend/Aggregator/Domains/DataTransferObjects/Photos/PhotoListDTO.cs  1
- src/backend/LamaAPI/Application/PhotoAlbums/Commands/DeleteAlbumPhotos/DeleteAlbumPhotosCommand.cs  1
- src/backend/LamaAPI/API/Controllers/PhotoAlbumsController.cs  1
- src/backend/Aggregator/Aggregator/ServicesConfiguration/EnvironmentConfiguration.cs  1
- src/backend/LamaAPI/Application/PhotoAlbums/Queries/GetAlbumPhotos/GetAlbumPhotosQuery.cs  1
- src/backend/Aggregator/HttpServices/Interceptors/HttpClientAuthorizationDelegatingHandler.cs  3
- src/backend/Aggregator/Aggregator/ServicesConfiguration/SwaggerConfiguration.cs  1
- src/backend/Aggregator/Domains/DataTransferObjects/Albums/AlbumListDTO.cs  1
- src/backend/LamaAPI/Application/Albums/Commands/CreateAlbum/CreateAlbumCommandValidator.cs  1
- src/backend/Aggregator/Aggregator/Startup.cs  1
- src/backend/LamaAPI/Domains/Entities/Album.cs  1
- src/backend/LamaAPI/API/Controllers/AlbumsController.cs  1
- src/backend/LamaAPI/API/ServicesConfigurations/ServicesConfiguration.cs  1
- src/backend/LamaAPI/Infrastructure/Migrations/20200216155454_AddAlbums.cs  1
- src/backend/LamaAPI/Application/PhotoAlbums/Commands/UpdateAlbumPhotos/UpdateAlbumPhotosCommandValidator.cs  1
- src/backend/LamaAPI/Application/PhotoAlbums/Events/ClearAlbumsOnPhotosDeletedEventHandler.cs  1
- src/backend/LamaAPI/Application/Albums/Commands/UpdateAlbum/UpdateAlbumCommandValidator.cs  1
- src/backend/Aggregator/AggregatorServices/Services/AlbumAggregator.cs  3
- src/backend/LamaAPI/Application/PhotoAlbums/Models/PhotoAlbumDTO.cs  1
- src/backend/LamaAPI/Application/Albums/AlbumProfile.cs  1
- src/backend/Aggregator/Aggregator/ServicesConfiguration/AggregatorConfiguration.cs  1
- src/backend/Aggregator/Domains/MappingProfiles/AlbumsProfile.cs  1
- src/backend/Aggregator/Domains/Aggregation/AlbumList.cs  1
- src/backend/LamaAPI/Application/Albums/Queries/GetCurrentUserAlbums/GetCurrentUserAlbumsQueryHandler.cs  1
- src/backend/Aggregator/Aggregator/ServicesConfiguration/CorsConfiguration.cs  1
- src/backend/LamaAPI/Application/PhotoAlbums/Commands/UpdateAlbumPhotos/UpdateAlbumPhotosCommand.cs  1
- src/backend/LamaAPI/Infrastructure/Configurations/AlbumConfiguration.cs  1
- src/backend/LamaAPI/Application/Albums/Models/AlbumList.cs  1
- src/backend/LamaAPI/Infrastructure/Migrations/20200216155454_AddAlbums.Designer.cs  1
- src/backend/LamaAPI/Application/Albums/Commands/DeleteAlbum/DeleteAlbumCommandHandler.cs  2
- src/backend/LamaAPI/Application/Albums/Commands/UpdateAlbum/UpdateAlbumCommand.cs  1
- src/backend/Aggregator/Aggregator/ServicesConfiguration/MapperConfiguration.cs  1
- src/backend/LamaAPI/Application/PhotoAlbums/Commands/UpdateAlbumPhotos/UpdateAlbumPhotosCommandHandler.cs  1
- src/backend/Aggregator/HttpServices/Configuration/UrlsConfiguration.cs  1
- src/backend/LamaAPI/Application/PhotoAlbums/PhotoAlbumProfile.cs  1
- src/backend/LamaAPI/API/ServicesConfigurations/MiddlewaresConfiguration.cs  1
- src/backend/LamaAPI/Application/Albums/Commands/CreateAlbum/CreateAlbumCommand.cs  1
- src/backend/Aggregator/Aggregator/Controllers/AlbumsController.cs  1
- src/backend/LamaAPI/Application/PhotoAlbums/Commands/DeleteAlbumPhotos/DeleteAlbumPhotosCommandHandler.cs  1
- src/backend/LamaAPI/Application/Albums/Commands/UpdateAlbum/UpdateAlbumCommandHandler.cs  2
- src/backend/Aggregator/Aggregator/ServicesConfiguration/AuthenticationConfiguration.cs  1
- src/backend/LamaAPI/Application/Albums/Commands/DeleteAlbum/DeleteAlbumCommand.cs  1
         

Clones added
============
- src/backend/Aggregator/Aggregator/Program.cs  2
- src/backend/Aggregator/Aggregator/ServicesConfiguration/EnvironmentConfiguration.cs  1
- src/backend/Aggregator/Aggregator/ServicesConfiguration/SwaggerConfiguration.cs  2
- src/backend/Aggregator/Aggregator/ServicesConfiguration/CorsConfiguration.cs  2
- src/backend/LamaAPI/Infrastructure/Migrations/ApplicationDbContextModelSnapshot.cs  2
- src/backend/LamaAPI/Infrastructure/Migrations/20200216155454_AddAlbums.Designer.cs  4
- src/backend/Aggregator/Aggregator/ServicesConfiguration/AuthenticationConfiguration.cs  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/iamprovidence/Lama/pullRequest?prid=5020178&bid=16548885)

File: src/backend/Aggregator/README.md [hunk 2]
```diff
@@ -0,0 +1,7 @@
+# Aggregator
+
+This microservice is responsible for collect data from other microservices and combine it to single model.
+
+## Architecture 
+
+* N-Layered
```
Comment (iamprovidence) [inline src/backend/Aggregator/README.md:7]: Codacy Issue found: [[list-item-indent] Incorrect list-item indent: add 2 spaces](https://app.codacy.com/manual/iamprovidence/Lama/pullRequest?prid=5020178)

File: src/backend/Aggregator/Aggregator/ServicesConfiguration/SwaggerConfiguration.cs [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+
+namespace Aggregator.ServicesConfiguration
+{
+    internal static class SwaggerConfiguration
+    {
+        public static void AddSwagger(this IServiceCollection services, IConfiguration configuration)
+        {
+            services.AddSwaggerGen(conf =>
+            {
+                conf.SwaggerDoc(name: "v1", info: new Info()
```
Comment (iamprovidence) [inline src/backend/Aggregator/Aggregator/ServicesConfiguration/SwaggerConfiguration.cs:19]: Codacy Issue found: [Remove these redundant parentheses.](https://app.codacy.com/manual/iamprovidence/Lama/pullRequest?prid=5020178)

File: src/backend/Aggregator/Domains/DataTransferObjects/Photos/PhotoListDTO.cs [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+        public string PhotoUrl256 { get; set; }
```
Comment (iamprovidence) [inline src/backend/Aggregator/Domains/DataTransferObjects/Photos/PhotoListDTO.cs:14]: Codacy Issue found: [Change this property type to 'System.Uri'.](https://app.codacy.com/manual/iamprovidence/Lama/pullRequest?prid=5020178)

File: src/backend/Aggregator/HttpServices/Interceptors/HttpClientAuthorizationDelegatingHandler.cs [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
+        {
+            string authorizationHeader = _httpContextAccesor
+                .HttpContext
+                .Request
+                .Headers["Authorization"];
+
+            if (!string.IsNullOrEmpty(authorizationHeader))
+            {
+                request.Headers.Add("Authorization", new List<string>() { authorizationHeader });
```
Comment (iamprovidence) [inline src/backend/Aggregator/HttpServices/Interceptors/HttpClientAuthorizationDelegatingHandler.cs:32]: Codacy Issue found: [Remove these redundant parentheses.](https://app.codacy.com/manual/iamprovidence/Lama/pullRequest?prid=5020178)

File: src/backend/Aggregator/Domains/Aggregation/AlbumList.cs [hunk 6]
```diff
@@ -0,0 +1,10 @@
+﻿namespace Domains.Aggregation
+{
+    public class AlbumList
+    {
+        public int Id { get; set; }
+        public string Title { get; set; }
+        public string CoverUrl { get; set; }
```
Comment (iamprovidence) [inline src/backend/Aggregator/Domains/Aggregation/AlbumList.cs:7]: Codacy Issue found: [Change this property type to 'System.Uri'.](https://app.codacy.com/manual/iamprovidence/Lama/pullRequest?prid=5020178)

File: src/backend/LamaAPI/Infrastructure/Migrations/20200216155454_AddAlbums.cs [hunk 7]
```diff
@@ -0,0 +1,64 @@
+﻿using System;
+using Microsoft.EntityFrameworkCore.Metadata;
+using Microsoft.EntityFrameworkCore.Migrations;
+
+namespace Infrastructure.Migrations
+{
+    public partial class AddAlbums : Migration
```
Comment (iamprovidence) [inline src/backend/LamaAPI/Infrastructure/Migrations/20200216155454_AddAlbums.cs:7]: Codacy Issue found: ['partial' is gratuitous in this context.](https://app.codacy.com/manual/iamprovidence/Lama/pullRequest?prid=5020178)

File: src/backend/Aggregator/HttpServices/Interceptors/HttpClientAuthorizationDelegatingHandler.cs [hunk 8]
```diff
@@ -0,0 +1,52 @@
...
+            }
+
+            string token = await GetToken();
```
Comment (iamprovidence) [inline src/backend/Aggregator/HttpServices/Interceptors/HttpClientAuthorizationDelegatingHandler.cs:35]: Codacy Issue found: [Add '.ConfigureAwait(false)' to this call to allow execution to continue in any thread.](https://app.codacy.com/manual/iamprovidence/Lama/pullRequest?prid=5020178)

File: src/backend/Aggregator/HttpServices/Extensions/HttpClientExtensions.cs [hunk 9]
```diff
@@ -0,0 +1,17 @@
+﻿using Newtonsoft.Json;
+
+using System.Net.Http;
+using System.Threading.Tasks;
+
+namespace HttpServices.Extensions
+{
+    public static class HttpClientExtensions
+    {
+        public static async Task<TResponse> GetAsync<TResponse> (this HttpClient httpClient, string url)
```
Comment (iamprovidence) [inline src/backend/Aggregator/HttpServices/Extensions/HttpClientExtensions.cs:10]: Codacy Issue found: [Either change this parameter type to 'System.Uri' or provide an overload which takes a 'System.Uri' parameter.](https://app.codacy.com/manual/iamprovidence/Lama/pullRequest?prid=5020178)

File: src/backend/Aggregator/Aggregator/ServicesConfiguration/SwaggerConfiguration.cs [hunk 10]
```diff
@@ -0,0 +1,57 @@
...
+                {
+                    Title = "Photo API",
+                    Version = "v1"
+                });
+                conf.AddAuthorization();
+            });
+        }
+
+        private static void AddAuthorization(this SwaggerGenOptions configuration)
```
Comment (iamprovidence) [inline src/backend/Aggregator/Aggregator/ServicesConfiguration/SwaggerConfiguration.cs:28]: Codacy Issue found: [Remove the unused private method 'AddAuthorization'.](https://app.codacy.com/manual/iamprovidence/Lama/pullRequest?prid=5020178)

File: src/backend/Aggregator/Aggregator/Program.cs [hunk 11]
```diff
@@ -0,0 +1,17 @@
+﻿using Microsoft.AspNetCore;
+using Microsoft.AspNetCore.Hosting;
+
+namespace Aggregator
+{
+    public class Program
```
Comment (iamprovidence) [inline src/backend/Aggregator/Aggregator/Program.cs:6]: Codacy Issue found: [Add a 'protected' constructor or the 'static' keyword to the class declaration.](https://app.codacy.com/manual/iamprovidence/Lama/pullRequest?prid=5020178)
